### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [o317p18/page-explorer#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by o317p18** [comment]
Thanks for mentioning, i will update the LICENSE right away! I decided to use MIT License as its easy to set up.

**Comment by TechnologyClassroom** [comment]
MIT is easiest, but not battle tested in the courts or copyleft.  For a [permissive license](https://en.wikipedia.org/wiki/Permissive_software_license), I would recommend [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) which is equally easy to apply.  GNU also recommends [Apache-2.0 for small programs](https://www.gnu.org/licenses/license-recommendations.html#small).

**Comment by o317p18** [comment]
Thanks a lot for your advice again! 
As i already did add the license i will keep it MIT. I will remember this for future projects though!.
